const UKR = [['titlename', 'Анастасія Бас'],
   ['personaldata', 'Особисті дані'],
   ['address', 'м.Черкаси, вул. Чайковського 50 кв. 95'],
   ['techskills', 'Технічні навички'],
   ['tskill1', 'MS Office'],
   ['mark1', 'Відмінно'],
   ['tskill2', 'Спеціалізовані правові системи'],
   ['mark2', 'Відмінно'],
   ['tskill3', '1С:Підприємство'],
   ['mark3', 'Добре'],
   ['tskill4', 'Оргтехніка'],
   ['mark4', 'Відмінно'],
   ['softskill', 'Комунікативні навички'],
   ['sskill1', 'Презентація'],
   ['mark5', 'Добре'],
   ['sskill2', 'Комунікація'],
   ['mark6', 'Добре'],
   ['sskill3', 'Організація'],
   ['mark7', 'Відмінно'],
   ['hobies', 'Інтереси'],
   ['hitem1', 'Інтернет-маркетинг'],
   ['hitem2', 'Здоровий спосіб життя'],
   ['lang', 'Мова'],
   ['langukr', 'Українська'],
   ['mark8', 'Відмінно'],
   ['langru', 'Російська'],
   ['mark9', 'Відмінно'],
   ['langen', 'Англійська'],
   ['mark10', 'Добре'],
   ['titlenamemain', 'Анастасія Бас'],
   ['aboutme', 'Про себе'],
   ['aboutmecontent', 'Мені 34 роки. Я мама двох дітей(8 і 5 років). Знаходжусь в пошуку роботи в сферах діловодства, юристпруденції або секретаріату. Дисциплінована, пунктуальна, люблю порядок в речах і справах, як на робочому місці, так і в особистому житті. Постійно слідкую за змінами та нововведеннями в законотворчій та юридичних сферах.'],
   ['experiencework', 'Досвід роботи'],
   ['poswork1', 'Касир-бухгалтер'],
   ['period1', 'Жовтень 2013 - Серпень 2015'],
   ['placework1', 'ПП Колега'],
   ['jobtask1', 'Приймання та облік фінансів підприємства.'],
   ['jobtask2', 'Ведення книги РРО.'],
   ['jobtask3', 'Видача заробітної плати співробітникам.'],
   ['poswork2', 'Документознавець'],
   ['period2', 'Квітень 2011 - Липень 2012'],
   ['placework2', 'ПП Колега'],
   ['jobtask4', 'Кадрове діловодство.'],
   ['jobtask5', 'Договірна робота.'],
   ['jobtask6', 'Забезпечення діяльності офісу.'],
   ['poswork3', 'Юрисконсульт'],
   ['period3', 'Листопад 2007 - Грудень 2009'],
   ['placework3', 'КП ВЖ РЕУ 2'],
   ['jobtask7', 'Представництво підприємства в судах.'],
   ['jobtask8', 'Претензійно-позовна робота.'],
   ['jobtask9', 'Надання консультацій в межах діяльності підприємства.'],
   ['edu', 'Освіта та кваліфікація'],
   ['spedu1', 'Юрист'],
   ['period4', 'Вересень 2007 - Грудень 2009'],
   ['eduplace1', 'Київський університет права ім. Корецького НАН'],
   ['edufac1', 'Цивільне та трудове право'],
   ['edulev1', 'Спеціаліст'],
   ['edufst1', 'Заочна форма навчання'],
   ['spedu2', 'Юрист'],
   ['period5', 'Вересень 2004 - Червень 2007'],
   ['eduplace2', 'Черкаський кооперативний економіко-правовий коледж'],
   ['edufac2', 'Правознавство'],
   ['edulev2', 'Молодший спеціаліст'],
   ['edufst2', 'Денна форма навчання']];
const mapUKR = new Map(UKR);
const RU = [['titlename', 'Анастасия Бас'],
   ['personaldata', 'Личные данные'],
   ['address', 'г.Черкассы, ул. Чайковського 50 кв. 95'],
   ['techskills', 'Техничные навыки'],
   ['tskill1', 'MS Office'],
   ['mark1', 'Отлично'],
   ['tskill2', 'Специализированые правовые системы'],
   ['mark2', 'Отлично'],
   ['tskill3', '1С:Предпринимательство'],
   ['mark3', 'Хорошо'],
   ['tskill4', 'Оргтехника'],
   ['mark4', 'Отлично'],
   ['softskill', 'Комуникативные навыки'],
   ['sskill1', 'Презентация'],
   ['mark5', 'Хорошо'],
   ['sskill2', 'Комуникация'],
   ['mark6', 'Хорошо'],
   ['sskill3', 'Организация'],
   ['mark7', 'Отлично'],
   ['hobies', 'Интересы'],
   ['hitem1', 'Интернет-маркетинг'],
   ['hitem2', 'Здоровый образ жизни'],
   ['lang', 'Язык'],
   ['langukr', 'Украинський'],
   ['mark8', 'Отлично'],
   ['langru', 'Русский'],
   ['mark9', 'Отлично'],
   ['langen', 'Английский'],
   ['mark10', 'Хорошо'],
   ['titlenamemain', 'Анастасия Бас'],
   ['aboutme', 'О себе'],
   ['aboutmecontent', 'Мне 34 года. Я мама двух детей(8 и 5 годиков). Нахожусь в поиске работи в сферах деловодства, юристпруденции или секретариата. Дисциплинированая, пунктуальная, люблю порядок в вещах и делах, как на рабочем месте, так и в личной жизни. Постояно слежу за изменениями и нововведенниями в законотворческой и юридической сферах.'],
   ['experiencework', 'Опыт работи'],
   ['poswork1', 'Касир-бухгалтер'],
   ['period1', 'Октябрь 2013 - Август 2015'],
   ['placework1', 'ЧП Колега'],
   ['jobtask1', 'Прийом и учёт финансов предприятия.'],
   ['jobtask2', 'Ведения книги РРО.'],
   ['jobtask3', 'Выдача зароботной платы работникам.'],
   ['poswork2', 'Документовед'],
   ['period2', 'Апрель 2011 - Июль 2012'],
   ['placework2', 'ЧП Колега'],
   ['jobtask4', 'Кадровое деловодство.'],
   ['jobtask5', 'Договорная работа.'],
   ['jobtask6', 'Обеспечение деятельности офиса.'],
   ['poswork3', 'Юрисконсульт'],
   ['period3', 'Ноябрь 2007 - Декабрь 2009'],
   ['placework3', 'КП ВЖ РЕУ 2'],
   ['jobtask7', 'Представительство предприятия в суддах.'],
   ['jobtask8', 'Претензионно-исковая работа.'],
   ['jobtask9', 'Предоставление консультаций в рамках деятельности предприятия.'],
   ['edu', 'Образование и квалификация'],
   ['spedu1', 'Юрист'],
   ['period4', 'Сентябрь 2007 - Декабрь 2009'],
   ['eduplace1', 'Киевский университет права им. Корецкого НАН'],
   ['edufac1', 'Гражданское и трудовое право'],
   ['edulev1', 'Специалист'],
   ['edufst1', 'Заочная форма обучения'],
   ['spedu2', 'Юрист'],
   ['period5', 'Сентябрь 2004 - Июнь 2007'],
   ['eduplace2', 'Черкасский кооперативный экономико-правовой колледж'],
   ['edufac2', 'Правоведение'],
   ['edulev2', 'Младший специалист'],
   ['edufst2', 'Дневная форма обучения']];
const mapRU = new Map(RU);
const ENG = [['titlename', 'Anastasiia Bas'],
   ['personaldata', 'Personal data'],
   ['address', 'Cherkasy, street Tchaikovsky 50 fl. 95'],
   ['techskills', 'Tech skills'],
   ['tskill1', 'MS Office'],
   ['mark1', 'Perfectly'],
   ['tskill2', 'Specialized legal systems'],
   ['mark2', 'Perfectly'],
   ['tskill3', '1С:Enterprise'],
   ['mark3', 'Good'],
   ['tskill4', 'Office equipment'],
   ['mark4', 'Perfectly'],
   ['softskill', 'Soft skills'],
   ['sskill1', 'Presentation'],
   ['mark5', 'Good'],
   ['sskill2', 'Communication'],
   ['mark6', 'Good'],
   ['sskill3', 'Organization'],
   ['mark7', 'Perfectly'],
   ['hobies', 'Hobies'],
   ['hitem1', 'Internet marketing'],
   ['hitem2', 'Healthy Lifestyle'],
   ['lang', 'Language'],
   ['langukr', 'Ukrainian'],
   ['mark8', 'Perfectly'],
   ['langru', 'Russian'],
   ['mark9', 'Perfectly'],
   ['langen', 'English'],
   ['mark10', 'Good'],
   ['titlenamemain', 'Anastasiia Bas'],
   ['aboutme', 'About me'],
   ['aboutmecontent', 'I am 34 years old. I am a mother of two children (8 and 5 years old). I am looking for a job in the fields of office work, jurisprudence or secretariat. Disciplined, punctual, I like order in things and affairs, both in the workplace and in personal life. I constantly follow changes and innovations in the legislative and legal spheres.'],
   ['experiencework', 'Experience'],
   ['poswork1', 'Cashier-accountant'],
   ['period1', 'October 2013 - August 2015'],
   ['placework1', 'Enterprise "Kolega"'],
   ['jobtask1', 'Acceptance and accounting of enterprise finances.'],
   ['jobtask2', 'Keeping a book RRO.'],
   ['jobtask3', 'Issuance of salaries to employees.'],
   ['poswork2', 'Documentary expert'],
   ['period2', 'April 2011 - July 2012'],
   ['placework2', 'Enterprise "Kolega"'],
   ['jobtask4', 'Personnel record keeping.'],
   ['jobtask5', 'Contract work.'],
   ['jobtask6', 'Ensuring office activities.'],
   ['poswork3', 'Legal adviser'],
   ['period3', 'November 2007 - December 2009'],
   ['placework3', 'KP VZH REU 2'],
   ['jobtask7', 'Representation of the enterprise in courts.'],
   ['jobtask8', 'Claim work.'],
   ['jobtask9', 'Providing advice within the enterprise.'],
   ['edu', 'Education and qualification'],
   ['spedu1', 'Lawyer'],
   ['period4', 'September 2007 - December 2009'],
   ['eduplace1', 'Kyiv University of Law named after Koretsky NAS'],
   ['edufac1', 'Civil and labor law'],
   ['edulev1', 'Specialist'],
   ['edufst1', 'External form of education'],
   ['spedu2', 'Lawyer'],
   ['period5', 'September 2004 - June 2007'],
   ['eduplace2', 'Cherkasy Cooperative College of Economics and Law'],
   ['edufac2', 'Science of law'],
   ['edulev2', 'Junior Specialist'],
   ['edufst2', 'Full-time education']];
const mapENG = new Map(ENG);